### ISSUE TITLE
Pass Protocol Compliance Test Suite

### ISSUE THREAD

**Issue by RangerMauve** [AgregoreWeb/agregore-mobile#16]
- [ ] Make sure [the suite](https://github.com/ipfs-shipyard/ipfs-protocol-compliance-suite) can load in Agregore Desktop (might require re-publishing it)
- [ ] Get the suite running on Agregore Mobile [with the rc1 release](https://build.mauve.moe/builds/AgregoreMobile-0.0.0-rc1.apk)
- [ ] See if all the [basic tests](https://github.com/ipfs-shipyard/ipfs-protocol-compliance-suite/blob/default/tests.js) pass
- [ ] Adjust the [mutability tests](https://github.com/ipfs-shipyard/ipfs-protocol-compliance-suite/blob/default/mutable-tests.js#L12) to account for the new way IPNS sites are created.
- [ ] Make the mutability tests pass

This process might involve adding fixes to the daemon and to the protocol handlers.

**Comment by makew0rld** [comment]
> Adjust the [mutability tests](https://github.com/ipfs-shipyard/ipfs-protocol-compliance-suite/blob/default/mutable-tests.js?rgh-link-date=2022-04-22T18%3A45%3A05Z#L12) to account for the new way IPNS sites are created.

Adjusting to match this [spec document](https://github.com/AgregoreWeb/agregore-ipfs-daemon/blob/0ec56165a43fcdd09e6cdbb5afcdd05e0ffd6428/spec.md). Work is happening on the [daemon-spec](https://github.com/AgregoreWeb/ipfs-protocol-compliance-suite/tree/daemon-spec) branch.

**Comment by makew0rld** [comment]
Made [PR](https://github.com/AgregoreWeb/ipfs-protocol-compliance-suite/pull/1) that just merges to the default branch of our fork. I figure a PR to the main IPFS can happen after all changes are accumulated.

**Comment by makew0rld** [comment]
## Running tests

### Agregore desktop

1. Start up Agregore
2. Load `ipns://ipfs.io` to confirm IPFS node is working
3. Enter test suite directory
4. `export IPFS_PATH=~/.config/agregore-browser/ipfs`
5. `./publish-files.js`
6. Visit IPFS URL outputted to confirm test files were loaded into Agregore
7. Run a web server to serve the test suite HTML: `python3 -m http.server`
8. Visit the web server: `http://127.0.0.1:8000`

### Agregore mobile

1. Follow the above steps, and leave the web server and Agregore desktop running
2. Open Agregore app
3. Load `ipns://ipfs.io` to confirm IPFS node is working
5. Set up [remote debugging](https://developer.chrome.com/docs/devtools/remote-debugging/) to control your phone from your computer, and read console output
6. Visit the IPFS URL of the test files, to ensure you have peered with desktop and can load files as needed
7. Visit the web server, using the IP address of your computer, for example: `http://192.168.50.123:8000`

**Comment by Madrets** [comment]
We're making additional changes to the protocol handlers so that we can get more of the tests in the test suite passing. Here are some of the things to look into:

- Use [HttpProtocolHandler](https://source.chromium.org/chromium/chromium/src/+/main:net/url_request/url_request_job_factory.cc;drc=1d8b1965b96c021ee069a3ebda38be7aaf8a5786;l=26) to handle `ipfs` and `ipns` URLs in [net/url_request/url_request_job_factory.cc](https://source.chromium.org/chromium/chromium/src/+/main:net/url_request/url_request_job_factory.cc;l=61).
- Make changes to `URLRequestHttpJob::Create()` in [net/url_request/url_request_http_job.cc](https://source.chromium.org/chromium/chromium/src/+/main:net/url_request/url_request_http_job.cc;l=192).
- We can look at what electron does for inspiration [here](https://github.com/electron/electron/blob/main/shell/browser/net/electron_url_loader_factory.cc).
- We can also look at related work done by the folks at Bromite [here](https://github.com/bromite/bromite/blob/master/build/patches/Block-qjz9zk-or-trk-requests.patch).

**Comment by Madrets** [comment]
Protocol handlers for `ipfs` and `ipns` that handle indirect URL requests (e.g. from JavaScript) have been added to `ipfs-protocol`. This is semi-experimental and additional changes are anticipated. We'll need to build and run the test suite again.

**Comment by RangerMauve** [comment]
We registered the protocols inside url_request_job_factory.cc as HTTPProtocolHandlers which rewrote `ipns` and `ipfs` urls to point to the gateway.

Now we have 29 tests passing, and 15 failing due to the URL scheme not being usable the the Fetch API.

In order to fix this we need to Use the [`WebSecurityPolicy::RegisterURLSchemeAsSupportingFetchAPI`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/exported/web_security_policy.cc;l=60;drc=f2fbc0135f4f2954f293099378379997b474246e;bpv=1;bpt=1) API, which we can add inside [`RenderThreadImpl::RegisterSchemes`](https://source.chromium.org/chromium/chromium/src/+/main:content/renderer/render_thread_impl.cc;l=988;drc=f2fbc0135f4f2954f293099378379997b474246e;bpv=1;bpt=1)

We'll probably also want to add [`RegisterURLSchemeAsWebUI`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/exported/web_security_policy.cc;drc=f2fbc0135f4f2954f293099378379997b474246e;bpv=1;bpt=1;l=152), [RegisterSchemeAsAllowingServiceWorkers](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/weborigin/scheme_registry.cc;drc=f2fbc0135f4f2954f293099378379997b474246e;bpv=1;bpt=1;l=264), [AddSchemeToSecureContextSafelist](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/public/web/web_security_policy.h;l=43;drc=f2fbc0135f4f2954f293099378379997b474246e;bpv=1;bpt=1?q=WebSecurityPolicy&ss=chromium%2Fchromium%2Fsrc)

Likely we'll also want to add [`ShouldTreatURLSchemeAsCorsEnabled`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/weborigin/scheme_registry.cc;l=264;drc=f2fbc0135f4f2954f293099378379997b474246e;bpv=1;bpt=1)

Hopefully this will be enough to get most of the other tests passing.

**Comment by RangerMauve** [comment]
We should generally look at all the `RegisterURLScheme` related things in this file in Electron to see if we need them: https://github.com/electron/electron/blob/main/shell/renderer/renderer_client_base.cc#L225

**Comment by RangerMauve** [comment]
We might also want to get rid of that top level redirect thing in favor of just the protocol schemes with the new permissions

**Comment by RangerMauve** [comment]
We've got 39 tests passing now.

iframes are still a bit iffy, and ServiceWorkers are still not available. But stuff like images and text and scripts is all working now. 🎉

One other weird thing, the web UI doesn't seem to think that `ipfs://` is a secure context even though we explicitly set it to be. Might also be related to why the ServiceWorkers aren't available even though we added them to the service_worker_schemes list inside the URLSchemeRegistry

**Comment by RangerMauve** [comment]
Looks like we'll also need to register the service worker schemes here: https://source.chromium.org/chromium/chromium/src/+/main:content/common/url_schemes.cc;l=114;drc=72186360334350c90b9b94515b3c82bea25e27ff

Found this by tracing the Electron API through here: https://github.com/electron/electron/blob/main/shell/browser/api/electron_api_protocol.cc#L96

**Comment by RangerMauve** [comment]
We will also need to add the secure schemes here: https://source.chromium.org/chromium/chromium/src/+/main:content/common/url_schemes.cc;l=73;drc=72186360334350c90b9b94515b3c82bea25e27ff

**Comment by RangerMauve** [comment]
We got 36/50 tests passing which is good enough. The last issues are to do with ServiceWorkers and stuff which we don't need to worry so much about.
