### ISSUE TITLE
Add custom protocol handlers

### ISSUE THREAD

**Issue by RangerMauve** [AgregoreWeb/agregore-mobile#2]
- [ ] Include custom protocols in [autocomplete settings](https://github.com/AgregoreWeb/agregore-mobile/compare/chromium...AgregoreWeb:kiwi#diff-39979775b46673b59d34a0b1fe5d67648209f63d8005ac1d8d894022d5a850b3R61), [url index](https://github.com/AgregoreWeb/agregore-mobile/compare/chromium...AgregoreWeb:kiwi#diff-39979775b46673b59d34a0b1fe5d67648209f63d8005ac1d8d894022d5a850b3R61), 
 - [ ] Add schemes to [url_constants](https://github.com/AgregoreWeb/agregore-mobile/compare/chromium...AgregoreWeb:kiwi#diff-7adf7e60402074a605aeb82d0a031eb9a8564cbc87645d892859feb6f8616c77R17)
 - [ ] Add to [url_pattern](https://github.com/AgregoreWeb/agregore-mobile/compare/chromium...AgregoreWeb:kiwi#diff-07c9e19ca40c37d48530525bc57576f2a17000d34ba0d7373254d297f075b5beR48)
 - [ ] Add to [kValidUserScriptSchemes](https://github.com/AgregoreWeb/agregore-mobile/compare/chromium...AgregoreWeb:kiwi#diff-87eaf868cd0727bebc04c51fa93a33e450cc1bb216ddb029c5a572734b3aee43R44)

**Comment by RangerMauve** [comment]
- [ ] figure out where the protocol handlers for `about://chrome` are registered
- [ ] Add a `agregore://theme/vars.css` page
- [ ] Add a `agregore://theme/style.css` page

Agregore protocol handler is in the desktop version here: https://github.com/AgregoreWeb/agregore-browser/blob/master/app/protocols/browser-protocol.js

Browser about handler here: https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/browser_about_handler.cc;drc=abfb8ff1b73192b2ffe220dcd7fbb597baf109bc;bpv=1;bpt=1;l=23

Here's where other handlers get registered: https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/chrome_content_browser_client.cc;l=3731;drc=4f70b046f82976388f68084840bd3e9b2811ec27;bpv=1;bpt=1

**Comment by Madrets** [comment]
Some special browser-level URLs like "about:version" are handled here: https://source.chromium.org/chromium/chromium/src/+/main:content/public/browser/browser_url_handler.h;drc=42e75824670baadf21ece40f71b946500af1cbce;l=25

**Comment by Madrets** [comment]
A new patch has been added to the `agregore-protocols` branch that implements `agregore://about`. We'll need to build to see if it works. Most of the changes were made in [chrome/browser/browser_about_handler.cc](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/browser_about_handler.cc;). The edited function is used [here](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/chrome_content_browser_client.cc;l=3731;drc=4f70b046f82976388f68084840bd3e9b2811ec27).


The other changes involved adding agregore-specific constants to the following (and their respective header files):

- [chrome/common/webui_url_constants.cc](https://source.chromium.org/chromium/chromium/src/+/main:chrome/common/webui_url_constants.cc;drc=7fb345a0da63049b102e1c0bcdc8d7831110e324;)
- [content/public/common/url_constants.cc](https://source.chromium.org/chromium/chromium/src/+/main:content/public/common/url_constants.cc)
#

URLs are implemented in [url/gurl.h](https://source.chromium.org/chromium/chromium/src/+/main:url/gurl.h;drc=7fb345a0da63049b102e1c0bcdc8d7831110e324;). Useful functions like `SchemeIs()`, `scheme()`, and `host()` can be found there.

URL constants can be found in [url/url_constants.cc](https://source.chromium.org/chromium/chromium/src/+/main:url/url_constants.cc;drc=7fb345a0da63049b102e1c0bcdc8d7831110e324;).

Direct URL changes may be made using functions in [url/url_canon_stdstring.h](https://source.chromium.org/chromium/chromium/src/+/main:url/url_canon_stdstring.h;).

**Comment by Madrets** [comment]
The following files have been updated in an attempt to register the `agregore` protocol:

- [content/common/url_schemes.cc](https://source.chromium.org/chromium/chromium/src/+/main:content/common/url_schemes.cc)
- [chrome/browser/profiles/profile_io_data.cc](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/profiles/profile_io_data.cc)

**Comment by RangerMauve** [comment]
@Madrets managed to get an initial `agregore://about` protocol handler working in #12 by rewriting the URL to `https://agregore.mauve.moe/` at runtime.

We're going to put the `agregore://` protocol handlers on hold and try to get `ipfs://` and `ipns://` working by using a similar method to rewrite them to point at `http://localhost:8080/ipfs/{HOSTNAME}/{PATH}`

After that we'll revisit theming while we test the capabilities of the protocol handlers.

**Comment by Madrets** [comment]
A new patch has been added to the `ipfs-protocol` branch that handles `ipfs` and `ipns` URLs.

**Comment by RangerMauve** [comment]
That's awesome! Would you mind rebasing your branch to exclude the commits related to the `agregore://` protocol handler stuff and the submitting a [pull request](https://github.com/AgregoreWeb/agregore-mobile/compare/default...ipfs-protocol) for so we can review before merging?

**Comment by RangerMauve** [comment]
The initial work for this is done via #14 Great work @Madrets !!

Next step is to test the protocol handlers to look for areas we need to add fixes to. #16
