### ISSUE TITLE
'hyper:' URLs not working

### ISSUE THREAD

**Issue by ProgrammerWhoPrograms** [AgregoreWeb/agregore-mobile#35]
Can't load `hyper://blog.mauve.moe/`, for example. It just searches for the URL in my search engine.
Same with `dat:` and `pear:`.

**Comment by RangerMauve** [comment]
Yup! Mobile only supports IPFS/IPNS right now. If you have leads on funding to get a new version made with hyper it'd be appreciated. Or if you have a bunch of spare time I could write up how to do it.
